POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q3QGV4YW1wbGUuY29tIiwiZXhwIjoxNzcyOTM1MDc4LCJ1c2VySWQiOjF9.M1GUn0fNqZLiCxN08y3pTRaIHBmmBQH3Vo_a5YhX-3o

{
    "name": "Angular 28 Event",
    "description": "Angular event at berlin",
    "location": "Tokyo",
    "dateTime": "2026-01-01T15:30:00.000Z"
}



