PUT http://localhost:8080/events/2
Content-Type: application/json

{
    "name": "Updated test event",
    "description": "A test event",
    "location": "Test location (updated)",
    "dateTime":"2026-01-01T15:30:00Z"
}